export * from './useInterval'
export * from './useSyncedState'
export * from './useIsMounted'
export * from './Logo'
export * from './Icons'
export * from './promisify'
export * from './pick'
export * from './useNumberOfBreath'
export * from './useBreathingPattern'
export const QUIZ_HOST = 'https://new.learnfirstquiz.com.ng' //'http://127.0.0.1:5000'
